apply plugin: 'com.android.application'

android {
    namespace 'com.xdtpl.smartgovtcalender'
    compileSdk 35

    defaultConfig {
        applicationId "com.xdtpl.smartgovtcalender"

        minSdk 24
        targetSdk 35

        versionCode 37
        versionName "6.5.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'
            ), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.annotation:annotation:1.8.2'

    // Material Components - required for NavigationView
    implementation 'com.google.android.material:material:1.12.0'

    // PDF
    implementation 'com.itextpdf:itextg:5.5.10'
//    implementation 'com.github.mhiew:android-pdf-viewer:3.2.0-beta.3'
    implementation 'com.github.alamin5g:Alamin5G-PDF-Viewer:v1.0.17'

    // Calendar
    implementation 'com.applandeo:material-calendar-view:1.9.2'

    // Networking
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'

    // HTML parser
    implementation 'org.jsoup:jsoup:1.17.2'

    // Existing local JAR
    implementation files('libs/poi-3.9.jar')

    androidTestImplementation "androidx.test.ext:junit:1.2.1"

    // Testing
    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    implementation 'androidx.fragment:fragment:1.8.5'
}